---
- name: "USER | Processing: {{ user.name }}"
  ansible.builtin.user:
    append: "{{ user.append | default('False') }}"
    name: "{{ user.name }}"
    state: "{{ user.state | default('present') }}"
    comment: "Ansible managed"
    password: "!"
    update_password: "always"
    password_lock: true
    shell: "{{ user.shell | default(omit) }}"
    group: "{{ admins_group }}"
    groups: "{{ user.groups | default(omit) }}"
    create_home: true
    system: false
    force: true
    remove: "{{ user.remove | default(true) }}"

- name: "USER | SSH keys: {{ user.name }}"
  ansible.posix.authorized_key:
    comment: "Ansible managed {{ user.name }}@{{ admins_group }}"
    exclusive: true
    key: "{{ lookup('file', admins_ssh_dir + '/' + user.name + '.pub') }}"
    follow: false
    user: "{{ user.name }}"
    manage_dir: true
    key_options: "{{ user.ssh_key_options | default(omit) }}"
    state: present
  when:
    - ( user.state | default('present') ) != 'absent'
